apiVersion: v1
kind: Pod
metadata:
  name: nginx-service
  labels:
    environment: production
    app: frontend
spec:
  containers:
  - name: nginx-pod
    image: nginx
    ports:
    - containerPort: 82
      name: my-port-web
---
apiVersion: v1
kind: Service
metadata:
  name: service-conf1
spec:
  selector:
    environment: production
    app: frontend    
  ports:
  - name: nginx
    protocol: TCP
    port: 82
    targetPort: my-port-web