apiVersion: v1
kind: Pod
metadata:
  name: nodeport-pod
  labels:
    name: nodeport1
    service: node
    environment: production
    app: frontend
spec:
  containers:
  - name: nodeport1
    image: nginx
    ports:
    - containerPort: 80
      name: dev-group
---
apiVersion: v1
kind: Service
metadata:
  name: nodeport-service
spec:
  type: NodePort
  selector:
    name: nodeport1
    service: node
    environment: production
    app: frontend
  ports:
  - name: nodeport-port
    port: 80
    targetPort: dev-group
    protocol: TCP

