apiVersion: v1
kind: Pod
metadata:
  name: load-balancer-pod
  labels:
    name: loadbalancer-pod
    environment: Developement
    app: frontend
spec:
  containers:
  - name: load-cont1
    image: nginx
    ports:
    - containerPort: 80
      name: web-app
---
apiVersion: v1
kind: Service
metadata:
  name: load-balancer
spec:
  type: LoadBalancer
  selector:
    name: loadbalancer-pod
    environment: Developement
    app: frontend
  ports:
  - name: load-balancer-service
    protocol: TCP
    port: 80
    targetPort: web-app