apiVersion: v1
kind: Pod
metadata:
  name: multiple-pod
  namespace: roboshop
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
  - name: nginx-support
    image: almalinux:8
    command: ["sleep", "200"]
