apiVersion: v1
kind: Pod
metadata:
  name: labels
  namespace: roboshop
  labels:
    environment: production
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80