apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-replicaset
  namespace: hari-namespace
spec:
  replicas: 11
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-container
        image: nginx:latest
        ports:
        - containerPort: 80
