global:
  scrape_interval: 60s # How frequently to scrape targets by default.
  scrape_timeout: 10s # How long until a scrape request times out.
  evaluation_interval: 60s # How frequently to evaluate rules.

rule_file:
  - "rules/01-rules.yaml" # Specify the path

alerting:
  alertmanager:
  - static_configs:
    - targets:
      - node1.cluster1.example.org
      - node2.cluster1.example.org
      - node3.cluster1.example.org
      - node1.cluster2.example.org
      - node2.cluster2.example.org
      - node3.cluster2.example.org
# A scrape configuration
scrape_configs:
  - job_name: prometheus
    honor_labels: true
    honor_timestamps: true
    scheme: http
    scrape_interval: 60s
    scrape_timeout: 55s
    metrics_path: /metrics
    static_configs:
    - targets: ['localhost:9090']
    - targets:
      - node1.cluster1.example.org
      - node2.cluster1.example.org
      - node3.cluster1.example.org
      - node1.cluster2.example.org
      - node2.cluster2.example.org
      - node3.cluster2.example.org