trigger:
pool:
stages:
  - stages:
      jobs:
      - job:
          steps:
            - step: 
          inputs:
          scripts:
environment: 


clientid: AI.8Q~jtlWA2CTPHuDb_hSBeYKRL5v1l4xPQEa_E
secretid: 2e5daa88-5b8d-46a3-ad57-184ce23d24e8

