apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-pod
  labels:
    environment: developement1
    tier: frontend1
    app: nginx1
spec:
  replicas: 3
  selector:
    matchLabels:
      environment: developement1
      tier: frontend1
      app: nginx1
  template:
    metadata:
      name: nginx-pod1
      labels:
        environment: developement1
        tier: frontend1
        app: nginx1
    spec:
      containers:
      - name: pod1
        image: nginx
        ports:
        - containerPort: 80

