FROM ubuntu:20.04
RUN apt-get update && apt-get install wget  -y && apt-get install -y gnupg && apt-get install -y wget gnupg openssl
RUN apt-get install apt-transport-https
RUN apt-get install openjdk-17-jdk -y
RUN apt-get install -y openjdk-8-jre
RUN wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | gpg --dearmor -o /usr/share/keyrings/elasticsearch-keyring.gpg
RUN echo "deb https://artifacts.elastic.co/packages/8.x/apt stable main" > /etc/apt/sources.list.d/elastic-8.x.list
RUN wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.12.2-amd64.deb \
    && wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.12.2-amd64.deb.sha512
RUN sha512sum -c elasticsearch-8.12.2-amd64.deb.sha512
RUN dpkg -i elasticsearch-8.12.2-amd64.deb
RUN apt-get install elasticsearch git python3 vim -y
EXPOSE 9200 9300
VOLUME /data
ENV ES_HOME /usr/share/elasticsearch
ENV ES_PATH_CONF /etc/elasticsearch
COPY elasticsearch.yml /etc/elasticsearch/elasticsearch.yml
USER elasticsearch
ENV PATH=$PATH:/usr/share/elasticsearch/bin

CMD ["elasticsearch"]

