AWSTemplateFormatVersion: "2010-09-09"
Description: "A simple CloudFormation template example"
Metadata:
  Author: "Your Name"
  Version: "1.0"

Parameters:
  EnvironmentType:
    Type: String
    Description: "Environment type for the resources"
    AllowedValues: ["Development", "Production"]
    Default: "Development"

Mappings:
  RegionMap:
    us-east-1:
      AMI: "ami-0c55b159cbfafe1f0"
    us-west-2:
      AMI: "ami-0323c3dd2da7fb37d"

Conditions:
  CreateProdResources: !Equals [!Ref EnvironmentType, "Production"]

Resources:
  MyEC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      InstanceType: "t2.micro"
      ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", AMI]

  MyS3Bucket:
    Type: "AWS::S3::Bucket"
    Condition: CreateProdResources
    Properties:
      BucketName: "production-bucket"
      AccessControl: "Private"

  MyDynamoDBTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: "my-table"
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

Outputs:
  EC2InstanceID:
    Description: "Instance ID of the created EC2 instance"
    Value: !Ref MyEC2Instance
  S3BucketName:
    Description: "S3 Bucket Name (Production only)"
    Value: !If [CreateProdResources, !Ref MyS3Bucket, "N/A"]
