Docker Session - 51:
	00:00: Docker Theory Concepts
	15:00: Docker Installation
	18:00: Adding user to docker group
	31:00: Port Forwarding in Docker
	40:00: Log into container
	43:34: naming to container
	47:00: Doubts Session
	59:00: docker alphine bare minimum image
	1hr:05: docker file

Docker Session - 52:
    00:00: Docker Installation
    10:00: LABEL Instruction
    19:00: Expose Instruction
    24:00: ENv Instruction
    38:00: Copy Instruction
    48:00: Docker Push Method
    56:00: Docker ADD Instruction
 01:05:00: Entry Point Instruction

Docker Session - 53:
    05:00: User Instruction
    11:00: Work Directory Instruction
    15:00: Arguments Instructions
    30:00: Onbuild Instructions
    40:00: Roboshop Web Component Building
 01:05:00: catalogue component building
 01:15:00: Mongodb Component Building

Docker Session - 54:
    Docker Compose Building
    Robo-shop Building All Components

Docker Session - 55:
    00:00: Docker Compose Files
    15:00: Docker Push All Images
    25:00: Docker Volumes UnNamed
    36:00: Named Volumes
    54:00: Best Practices
 01:14:00: MultiStage Building
 01:20:00: Run Container as Non Root user

Docker Session - 56:
    00:00: Docker Architecture
    10:00: Docker Layers
    28:00: Docker Disadvantages
    31:00: Container Orchestration