What is GitLab :
- Code Management
- Continuous Integration
- Continuous Delivery System
- Open Source Commercial Options Available

Publish-Subscribe Model:
- A Highly available durable secure fully managed pub/sub messaging service that enables you to decouple microservices,distributed systems and serverless applications

Continuous Integration:
- In Continuous Integration We can merge the developers code into the repository
- Collaboration
- Improved Delivery
- Security
- Speed
- Scale Reliability

Continuous Development:
-

