apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app1
  template:
    metadata:
      name: my-app1-pod
      labels:
        app: my-app1
    spec:
      containers:
        - name: my-app1
          image: ghcr.io/stacksimplify/kubenginxhelm:0.1.0
          ports:
            - containerPort: 80

