# 1. Create Config Map
# 2. Create a Multicontainer Pod
# 3. Create a Volume with emptyDir and Mount to the containers
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-filebeat
data:
  filebeat.yml: | 
    filebeat:
      config:
        modules:
          path: /usr/share/filebeat/modules.d/*.yml
          reload:
            enabled: true
      modules:
      - module: nginx
        access:
          var.paths: ["/var/log/nginx/access.log*"]
        error:
          var.paths: ["/var/log/nginx/error.log*"]
    output:
      elasticsearch:
        hosts: ["elasticsearch:9200"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: filebeat-pod
  labels:
    environment: development
spec:
  replicas: 1
  selector:
    matchLabels:
      environment: developement
      app: nginx-pod
      tier: db
  template:
    metadata:
      name: filebeat-containers
      labels:
        environment: developement
        app: nginx-pod
        tier: db
    spec:
      volumes:  # This is Volume Creation for the pods
        - name: nginx-logs
          emptyDir: {}
        - name: filebeat-logs
          configMap:
            name: configmap-filebeat
            items:
            - key: filebeat.yml
              path: filebeat.yml
      containers:
      - name: main-container
        image: nginx
        volumeMounts:
        - name: nginx-logs
          mountPath: var/log/nginx/
      - name: filebeat-sidecar
        image: docker.elastic.co/beats/filebeat:7.5.0
        volumeMounts:
        - name: nginx-logs
          mountPath: var/log/nginx/
        - name: filebeat-logs
          mountPath: /usr/share/filebeat/filebeat.yml
          subPath: filebeat.yml

      
