apiVersion: v1
kind: Pod
metadata:
  name: configmap-demo
spec:
  containers:
  - name: config-container
    image: nginx
    env:
    - name: COURSE
      valueFrom:
        configMapKeyRef:
          name: course-config
          key: COURSE
    - name: DURATION
      valueFrom:
        configMapKeyRef:
          name: course-config
          key: DURATION