apiVersion: v1
kind: Pod
metadata:
  name: config-direct
spec:
  containers:
  - name: config-pod-d
    image: nginx
    envFrom:
    - configMapRef:
        name: configmap
---
apiVersion: v1
kind: Pod
metadata:
  name: any-name
spec:
  containers:
  - name: devops-container1
    image: nginx
    ports:
    - containerPort: 80
    envFrom:
    - configMapRef:
        name: configmap
  - name: devops-container2
    image: almalinux:8
    ports:
    - containerPort: 81
    envFrom:
    - configMapRef:
        name: configmap