apiVersion: v1
kind: Secret
metadata:
  name: secret-map
data:
  username: cGVkZGlyZWRkeTEK
  password: Y2hpeXlhcGFkdQo=
---
apiVersion: v1
kind: Pod
metadata: 
  name: secret-config-map
spec:
  containers:
  - name: secret-cont1
    image: nginx
    ports:
    - containerPort: 80
    envFrom:
    - secretRef:
        name: secret-map
---
apiVersion: v1
kind: Pod
metadata:
  name: secret-config-map1
spec:
  containers:
  - name: secret-cont2
    image: nginx
    ports:
    - containerPort: 81
    env:
    - name: username
      valueFrom:
        secretKeyRef:
          name: secret-map
          key: username
    - name: password
      valueFrom:
        secretKeyRef:
          name: secret-map
          key: password
---
apiVersion: v1
kind: Pod
metadata:
  name: secret-pod1
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: username
      valueFrom:
        secretKeyRef:
          name: secret-map
          key: username
    envFrom:
    - secretRef:
        name: secret-map


