---
apiVersion: v1
kind: Namespace
metadata:
  name: myfirst
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: myfirst
spec:
  containers:
  - name: nginx-pod
    image: nginx:1.14.2
    ports:
    - containerPort: 80
