pipeline {
    agent {node {label 'agent1' }}
    options {
        ansiColor('xterm')
        timeout (time: 1, unit: 'HOURS')
    }
    parameters {
        string(name: 'PERSON', defaultValue: 'Mr Jenkins', description: 'Who should I say hello to?')
        text(name: 'BIOGRAPHY', defaultValue: '', description: 'Enter some information about the person')
        booleanParam(name: 'TOGGLE', defaultValue: true, description: 'Toggle this value')
        choice(name: 'CHOICE', choices: ['One', 'Two', 'Three'], description: 'Pick something')
        password(name: 'PASSWORD', defaultValue: 'SECRET', description: 'Enter a password')
    }
    environment{
        USER = 'peddireddy'
    }
    stages{
        stage('Init'){
            steps{
                sh '''
                ls -ltr
                pwd
                print(env)
                echo $USER
                '''
            when {
                branch "master"
            }
            if(params.USER == 'peddireddy')
            {
                steps {
                    sh '''
                    echo "Building Pipeline
                    '''
                }
            }
            }
        }
        stage ('paln'){
            steps {
                sh '''
                ls- ltr
                cd etc
                ls -ltr
                '''
            }
        }
        stage('Approve') {
            steps {
                input "Please Approve the Request?"
            }
        }
    }
    post {
        always {
            echo "execute all the time this senstences"
        }
        failure {
            echo "the execution got failed due to some issues"
        }
    }
}