ETCD Detailed Explanation: Etcd port - 2379
a storage system for k8s related information
key-value store

ETCD stores data in the form of JSON /YAML

We can download the binaries and extract it and run it
to store the data in etcd run command: ./etcdctl set key1 value1
to retrieve data : ./etcdctl get key1 -- value1

ETCD Versions:
v0.1 - 2013
v0.2 - 2014
v2.0 - 2015
v3.1 - 2017
CNCF - 2018

./etcdctl --version
ETCD: Stores all information related to pods,replicasets, Nodes,secrets, configmap,daemonsets roles,role-bindings etc..

ETCD : it is a Service
ETCDCTL is the CLI tool used to interact with ETCD.

For example ETCDCTL version 2 supports the following commands:

etcdctl backup
etcdctl cluster-health
etcdctl mk
etcdctl mkdir
etcdctl set


Whereas the commands are different in version 3:

etcdctl snapshot save
etcdctl endpoint health
etcdctl get
etcdctl put

To set the right version of API set the environment variable ETCDCTL_API command: export ETCDCTL_API=3

Location for ETCD: /etc/kubernetes/pki/ca.crt



