Jenkins Secret Management:
What is environment directive:
Sequence Of Key-value Pairs
Define as Environment Variable
for all Steps and Stages,Specific Steps etc

Using Credentials Method :
    Environment Directive Supports a sprecial Helper Method
    credentials()
    used to access pre-defined credentials by their identifier in the jenkins Environment
Supported Credentials Type:
    Secret text
    Secret File
    Username and password
    SSH with Private Key
    Certificates

1: Go to manage jenkins
2: Go To Credentials
3: Go to System variables
4: Go to Global Credntails


Pipeline:
    we can define Environment variables:
        locally : inside stages,Steps
        globally: inside pipelines

    pipeline {
    agent any
    stages {
        stage('hello'){
            environment {
            var1 = "test-password"
            }
         step {
               echo "testing the environement varaibel"
         }
        }
       }
      }

Using The Credentials Stored in jenkins Credntials:
   pipeline {
agent any
stages {
    stage('hello'){
        environment {token = Credentials('token-anme')}
     step {
          sh ''' echo "$token" '''
     }
    }
   }
  }

############################################

# Secrets Management:

  It is related to store the sensitive information

Hashi-Corp Vault:
  sudo apt install vault
  vault server -dev -dev-listen-address="ip-address"

Secret Engine:
  The engine where we can able to create different type of secrets in hashicorp
  Secrets engines are Vault components which store, generate or encrypt secrets. Like Key/Value Pairs

  KV-Secret Engine,PKI Certificates,SSH etcc...

  Create a Role in Hashi Corp Vault that allow the policies
    approle, oidc, username&password
vault policy write terraform - <<EOF

role-id

provider "vault" {
  address = "ip-address"
  skip_child_token = true
  auth_login {
     path = "auth/approle/login"
  }
  parameters = {
    role_id = "role-id"
    secret_id = "secret_id"
  }
}

# Secret Management on AWS :
    1: Systems Manager Parameters Store(Systems Manager)
    2: Secrets Manager
    3: Hashi-Corp Vault (not aws offering)

Systems Manager: (If the passwords is secure but not highly secure)
    Parameters Store (Easily Retirve the Values)

Secrets Manager: # Rotating the information
Ceritificates should be rotated once every 180 days
Password related to db related password should be Rotated once every 90 days


1: Rotation
2: Integrate with lambda functions
3: We can store the value related to DataBases


DataBase Passwords
API Tokens

Secrets Managers is high cost
To sure high security credentials

Need to Store: Secrets manager
in ci cd pipeline we need to build these secrets Management to secure the credentials

    1: Container registry login
    2: Conatiner registry password
    3: Container Registry url

1: User Name and URL can be stored in the # Systems Manager
2: Password would be stored in the # Secrets Manager


Hashi-Corp Vault:
    Hashi-Corp Vault is dedicated secrets manager
    Open Source
    Highly Secure
    Good Community Support
    High Encryption Model
    Community Model Project to Store Secrets like passowrd.
    For Multi-Cloud Environment
