apiVersion: v1
kind: Pod
metadata:
  name: myapp-service
  namespace: india
  labels:
    app: my-app
    type: frontend
spec:
  containers:
  - name: front-end-app
    image: nginx
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  namespace: india
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30008
  selectors:
    app: my-app
    type: frontend
