name: Terraform Pipeline

on:
  push:
    branches:
      - main

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Terraform Init
        run: echo "hello"

      - name: Terraform Plan
        run: echo "hello"

  wait_for_approval_and_apply:
    needs: plan
    runs-on: ubuntu-latest
    environment:
      name: manual-approval  # 👈 This triggers the wait for approval
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Terraform Apply
        run: echo "hello"
