name: Testing Push Event
on: push
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Getting The code
        uses: actions/checkout@v3
      - name: Download NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install Dependencies
        run: |
         pwd
         cd ../
         pwd
      - name: Run test
        run: cd ../
        

        