name: Testing Push Event
on: push
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Getting The code
        uses: actions/checkout@v3
      - name: Download NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install Dependencies
        run: |
         pwd
         cd ../
         pwd
         ls -ltr
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Getting The code
        uses: actions/checkout@v3
      - name: Checking the code
        run : ls -ltr
      - name: change the directory
        run : cd ../
      - name: again check the code
        run:  ls -ltr

  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check the repo 
        run: pwd
      
        

        